apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-custom
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-custom
    app.kubernetes.io/part-of: partner-catalog-custom
  name: partner-catalog-custom
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-custom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-custom
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jbaxter1-tenant/partner-catalog-custom/partner-catalog-custom@sha256:3bc4e5cf4c470c434a2fd79c4c18c80b5f65fbad1f5a758074c5d51e0d7b81e0
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
