apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-custom
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jbaxter1-tenant/partner-catalog-custom/partner-catalog-custom@sha256:3bc4e5cf4c470c434a2fd79c4c18c80b5f65fbad1f5a758074c5d51e0d7b81e0
        name: my-java-springboot
        resources: {}
status: {}
